# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FoSIL
email: # fosil@hs-mittweida.de
description: >- # this means to ignore newlines until "baseurl:"
  Forensic Science Investigation Lab
baseurl: "/fosil" # the subpath of your site, e.g. /blog
url: "https://forensic-science-investigation-lab.github.io/fosil/" # the base hostname & protocol for your site, e.g. http://example.com
favicon-url: "/assets/images/brand/favicon.png"
instagram_username: forensik.studyweida
permalink: /:collection/:title/

# Collections
collections:
    courses:
        output: true
        permalink: /courses/:title/
    news:
        output: true
        permalink: /:title/
        sort_by: sort-weight
    team-members:
        output: true
        permalink: /about/team/:title/
    theses:
        output: true
        permalink: /students/:title/
    
# Defaults
author: "Das FoSIL-Team" # a default to place when author field is not specified

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      background: "/assets/images/backgrounds/network-4851079_1920.jpg"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      background: "/assets/images/backgrounds/network-4851079_1920.jpg"
  -
    scope:
        path: ""
        type: "workshops"
    values:
        layout: "workshop" 
        background: "/assets/images/backgrounds/network-4851079_1920.jpg"
  -
    scope:
        path: ""
        type: "news"
    values:
        layout: "news" 
        background: "/assets/images/backgrounds/network-4851079_1920.jpg"
  -
    scope:
        path: ""
        type: "handouts"
    values:
        layout: "handout" 
        background: "/assets/images/backgrounds/network-4851079_1920.jpg"
  -
    scope:
        path: ""
        type: "team-members"
    values:
        layout: "team-member" 
        background: "/assets/images/backgrounds/network-4851079_1920.jpg"
  -
    scope:
        path: ""
        type: "theses"
    values:
        layout: "theses" 
        background: "/assets/images/backgrounds/network-4851079_1920.jpg"

# Build settings
markdown: kramdown
# theme: jekyll-theme-clean-blog
# adapated from https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/